spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
