CREATE TABLE TASK
(
    ID           INT            AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITLE        VARCHAR(255)   NOT NULL,
    DESCRIPTION  VARCHAR(255)   NOT NULL,
    START_DATE   DATE           NOT NULL,
    PRIORITY     INT            NOT NULL
);
